INSERT INTO TIPO_CAMBIO VALUES (1, 'SOL','USD','/', 3.90);
INSERT INTO TIPO_CAMBIO VALUES (2, 'USD','SOL','*', 3.90);
INSERT INTO TIPO_CAMBIO VALUES (3, 'USD','EUR','/' , 1.19);
INSERT INTO TIPO_CAMBIO VALUES (4, 'EUR','USD','*' , 1.19);
INSERT INTO TIPO_CAMBIO VALUES (5, 'SOL','MXN','*' , 5.07);
INSERT INTO TIPO_CAMBIO VALUES (6, 'MXN','SOL','/' , 5.07);
INSERT INTO TIPO_CAMBIO VALUES (7, 'SOL','JPY','/' , 28.45);
INSERT INTO TIPO_CAMBIO VALUES (8, 'JPY','SOL','/' , 28.45);